### ISSUE TITLE
RGB images

### ISSUE THREAD

**Issue by liuyulvv** [p2irc/rgb2nir#1]
As can be seen from the Figure1 in your paper, your imaging device has only 5 sensors, blue, green, red, nir and red edge, respectively.

Are the RGB images you use composed of blue, green and red grayscale images?

**Comment by bia006** [comment]
The Micasense sensor used in our study captures blue, green, red, nir and rededge spectral bands. RGB images used in the study are a composite of R, G, B bands taken by the Micasense sensor.
